// <auto-generated />
namespace Bike_Share.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class removeworkshop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeworkshop));
        
        string IMigrationMetadata.Id
        {
            get { return "201505170410020_remove-workshop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
