// <auto-generated />
namespace Bike_Share.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prebugbashsept192015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prebugbashsept192015));
        
        string IMigrationMetadata.Id
        {
            get { return "201509191527228_pre-bug-bash=-sept-19-2015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
