// <auto-generated />
namespace Bike_Share.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GoogleMapsAnalyticsAtRuntime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoogleMapsAnalyticsAtRuntime));
        
        string IMigrationMetadata.Id
        {
            get { return "201509200221301_Google-Maps-Analytics-At-Runtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
